# Generated by Django 3.0.8 on 2020-07-28 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0002_bug_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='bugSolver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugSolverBug', to='bugtrack.Solver'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
