# Generated by Django 3.0.8 on 2020-07-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0003_auto_20200728_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='fix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
