# Generated by Django 3.0.8 on 2020-07-30 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0006_auto_20200730_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bugPoster', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
