# Generated by Django 3.0.8 on 2020-08-04 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0008_auto_20200730_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtrack.Update')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
