# Generated by Django 3.0.8 on 2020-08-04 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0009_updatecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updateComment', to='bugtrack.UpdateComment'),
        ),
    ]
