# Generated by Django 3.0.8 on 2020-08-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0010_update_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='solver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateSolver', to='bugtrack.Solver'),
        ),
    ]
