# Generated by Django 3.0.8 on 2020-08-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0011_auto_20200805_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bugsSolved',
        ),
        migrations.AddField(
            model_name='user',
            name='bugsSolved',
            field=models.ManyToManyField(related_name='userSolved', to='bugtrack.Solver'),
        ),
    ]
