# Generated by Django 3.0.8 on 2020-08-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0012_auto_20200807_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='status',
            field=models.CharField(default='low', max_length=50),
            preserve_default=False,
        ),
    ]
