# Generated by Django 3.0.8 on 2020-08-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0013_update_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
