# Generated by Django 3.0.8 on 2020-08-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0016_auto_20200829_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notifType',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notification',
        ),
        migrations.AddField(
            model_name='update',
            name='notifRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='update',
            name='notifType',
            field=models.CharField(blank=True, default='none', max_length=50, null=True),
        ),
    ]
