# Generated by Django 3.0.8 on 2020-09-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0017_auto_20200831_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='newNotif',
            field=models.BooleanField(default=False),
        ),
    ]
