# Generated by Django 3.0.8 on 2020-10-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0018_bug_newnotif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='updates',
        ),
        migrations.AddField(
            model_name='bug',
            name='updates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugUpdate', to='bugtrack.Update'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='bugsSolved',
        ),
        migrations.AddField(
            model_name='user',
            name='bugsSolved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userSolved', to='bugtrack.Solver'),
        ),
    ]
